---
AWSTemplateFormatVersion: 2010-09-09

Resources:
  OrderRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: messaging-arch/order-service
  InvoiceRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: messaging-arch/invoice-service
  DeliveryRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: messaging-arch/delivery-service

Outputs:
  OrderRepositoryArn:
    Value: !GetAtt OrderRepository.Arn
  InvoiceRepositoryArn:
    Value: !GetAtt InvoiceRepository.Arn
  DeliveryRepositoryArn:
    Value: !GetAtt DeliveryRepository.Arn
