
---
AWSTemplateFormatVersion: 2010-09-09

Resources:
  Key:
    Type: AWS::KMS::Key
    Properties:
      Description: kms key
      KeyPolicy:
        Version: 2012-10-17
        Id: allow-root-access-to-key
        Statement:
        - Sid: allow-root-to-delegate-actions
          Effect: Allow
          Principal:
            AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
          Action:
          - kms:*
          Resource: '*'

  KeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: alias/messaging-arch-kms
      TargetKeyId: !Ref Key

  OrderSecretKeyBase:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: production_key_base
      KmsKeyId: !Ref Key
      Name: !Sub ${AWS::StackName}-order-secret-key-base

  OrderDatabaseUrl:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: database_url
      KmsKeyId: !Ref Key
      Name: !Sub ${AWS::StackName}-order-database-url

  InvoiceSecretKeyBase:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: production_key_base
      KmsKeyId: !Ref Key
      Name: !Sub ${AWS::StackName}-invoice-secret-key-base

  InvoiceDatabaseUrl:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: database_url
      KmsKeyId: !Ref Key
      Name: !Sub ${AWS::StackName}-invoice-database-url

  DeliverySecretKeyBase:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: production_key_base
      KmsKeyId: !Ref Key
      Name: !Sub ${AWS::StackName}-delivery-secret-key-base

  DeliveryDatabaseUrl:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: database_url
      KmsKeyId: !Ref Key
      Name: !Sub ${AWS::StackName}-delivery-database-url

Outputs:
  OrderSecretKeyBase:
    Value: !Ref OrderSecretKeyBase
  OrderDatabaseUrl:
    Value: !Ref OrderDatabaseUrl
  InvoiceSecretKeyBase:
    Value: !Ref InvoiceSecretKeyBase
  InvoiceDatabaseUrl:
    Value: !Ref InvoiceDatabaseUrl
  DeliverySecretKeyBase:
    Value: !Ref DeliverySecretKeyBase
  DeliveryDatabaseUrl:
    Value: !Ref DeliveryDatabaseUrl
